# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import sys
sys.path.append('..')
from GRPCConsul import GrpcConsul_pb2 as GrpcConsul__pb2


class GrpcConsulHelperStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Test = channel.unary_unary(
        '/GrpcConsulHelper/Test',
        request_serializer=GrpcConsul__pb2.Request.SerializeToString,
        response_deserializer=GrpcConsul__pb2.Response.FromString,
        )


class GrpcConsulHelperServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GrpcConsulHelperServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Test': grpc.unary_unary_rpc_method_handler(
          servicer.Test,
          request_deserializer=GrpcConsul__pb2.Request.FromString,
          response_serializer=GrpcConsul__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GrpcConsulHelper', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
