# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LogHelper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LogHelper.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fLogHelper.proto\"d\n\tInRequest\x12\x0e\n\x06IpAddr\x18\x01 \x01(\t\x12\r\n\x05\x43\x44\x61te\x18\x02 \x01(\t\x12\x18\n\x05Level\x18\x03 \x01(\x0e\x32\t.LogLevel\x12\r\n\x05Title\x18\x04 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x05 \x01(\t\"=\n\x0bOutResponse\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x05\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\t*,\n\x08LogLevel\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\x33\n\tLogHelper\x12&\n\x08WriteLog\x12\n.InRequest\x1a\x0c.OutResponse\"\x00\x62\x06proto3')
)

_LOGLEVEL = _descriptor.EnumDescriptor(
  name='LogLevel',
  full_name='LogLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INFO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=184,
  serialized_end=228,
)
_sym_db.RegisterEnumDescriptor(_LOGLEVEL)

LogLevel = enum_type_wrapper.EnumTypeWrapper(_LOGLEVEL)
INFO = 0
WARNING = 1
ERROR = 2



_INREQUEST = _descriptor.Descriptor(
  name='InRequest',
  full_name='InRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IpAddr', full_name='InRequest.IpAddr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CDate', full_name='InRequest.CDate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Level', full_name='InRequest.Level', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Title', full_name='InRequest.Title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='InRequest.Content', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=119,
)


_OUTRESPONSE = _descriptor.Descriptor(
  name='OutResponse',
  full_name='OutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='OutResponse.Code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='OutResponse.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='OutResponse.Content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=182,
)

_INREQUEST.fields_by_name['Level'].enum_type = _LOGLEVEL
DESCRIPTOR.message_types_by_name['InRequest'] = _INREQUEST
DESCRIPTOR.message_types_by_name['OutResponse'] = _OUTRESPONSE
DESCRIPTOR.enum_types_by_name['LogLevel'] = _LOGLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InRequest = _reflection.GeneratedProtocolMessageType('InRequest', (_message.Message,), dict(
  DESCRIPTOR = _INREQUEST,
  __module__ = 'LogHelper_pb2'
  # @@protoc_insertion_point(class_scope:InRequest)
  ))
_sym_db.RegisterMessage(InRequest)

OutResponse = _reflection.GeneratedProtocolMessageType('OutResponse', (_message.Message,), dict(
  DESCRIPTOR = _OUTRESPONSE,
  __module__ = 'LogHelper_pb2'
  # @@protoc_insertion_point(class_scope:OutResponse)
  ))
_sym_db.RegisterMessage(OutResponse)



_LOGHELPER = _descriptor.ServiceDescriptor(
  name='LogHelper',
  full_name='LogHelper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=230,
  serialized_end=281,
  methods=[
  _descriptor.MethodDescriptor(
    name='WriteLog',
    full_name='LogHelper.WriteLog',
    index=0,
    containing_service=None,
    input_type=_INREQUEST,
    output_type=_OUTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGHELPER)

DESCRIPTOR.services_by_name['LogHelper'] = _LOGHELPER

# @@protoc_insertion_point(module_scope)
