# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SSOVerifyLogin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SSOVerifyLogin.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14SSOVerifyLogin.proto\"8\n\x12VerifyLoginRequest\x12\x10\n\x08UserName\x18\x01 \x01(\t\x12\x10\n\x08PassWord\x18\x02 \x01(\t\"N\n\x13VerifyLoginResponse\x12\x15\n\x04\x43ode\x18\x01 \x01(\x0e\x32\x07.Status\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\t*\x1c\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x46\x61iled\x10\x01\x32L\n\x0eSSOVerifyLogin\x12:\n\x0bVerifyLogin\x12\x13.VerifyLoginRequest\x1a\x14.VerifyLoginResponse\"\x00\x62\x06proto3')
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=162,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
OK = 0
Failed = 1



_VERIFYLOGINREQUEST = _descriptor.Descriptor(
  name='VerifyLoginRequest',
  full_name='VerifyLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserName', full_name='VerifyLoginRequest.UserName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PassWord', full_name='VerifyLoginRequest.PassWord', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=80,
)


_VERIFYLOGINRESPONSE = _descriptor.Descriptor(
  name='VerifyLoginResponse',
  full_name='VerifyLoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='VerifyLoginResponse.Code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='VerifyLoginResponse.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='VerifyLoginResponse.Content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=160,
)

_VERIFYLOGINRESPONSE.fields_by_name['Code'].enum_type = _STATUS
DESCRIPTOR.message_types_by_name['VerifyLoginRequest'] = _VERIFYLOGINREQUEST
DESCRIPTOR.message_types_by_name['VerifyLoginResponse'] = _VERIFYLOGINRESPONSE
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerifyLoginRequest = _reflection.GeneratedProtocolMessageType('VerifyLoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYLOGINREQUEST,
  __module__ = 'SSOVerifyLogin_pb2'
  # @@protoc_insertion_point(class_scope:VerifyLoginRequest)
  ))
_sym_db.RegisterMessage(VerifyLoginRequest)

VerifyLoginResponse = _reflection.GeneratedProtocolMessageType('VerifyLoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYLOGINRESPONSE,
  __module__ = 'SSOVerifyLogin_pb2'
  # @@protoc_insertion_point(class_scope:VerifyLoginResponse)
  ))
_sym_db.RegisterMessage(VerifyLoginResponse)



_SSOVERIFYLOGIN = _descriptor.ServiceDescriptor(
  name='SSOVerifyLogin',
  full_name='SSOVerifyLogin',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=192,
  serialized_end=268,
  methods=[
  _descriptor.MethodDescriptor(
    name='VerifyLogin',
    full_name='SSOVerifyLogin.VerifyLogin',
    index=0,
    containing_service=None,
    input_type=_VERIFYLOGINREQUEST,
    output_type=_VERIFYLOGINRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SSOVERIFYLOGIN)

DESCRIPTOR.services_by_name['SSOVerifyLogin'] = _SSOVERIFYLOGIN

# @@protoc_insertion_point(module_scope)
