# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SSOVerifyUrl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SSOVerifyUrl.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12SSOVerifyUrl.proto\"7\n\x0fVerifyInRequest\x12\x12\n\nRequestUrl\x18\x01 \x01(\t\x12\x10\n\x08TicketId\x18\x02 \x01(\t\"C\n\x11VerifyOutResponse\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x05\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\t2C\n\x0cSSOVerifyUrl\x12\x33\n\tVerifyUrl\x12\x10.VerifyInRequest\x1a\x12.VerifyOutResponse\"\x00\x62\x06proto3')
)




_VERIFYINREQUEST = _descriptor.Descriptor(
  name='VerifyInRequest',
  full_name='VerifyInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RequestUrl', full_name='VerifyInRequest.RequestUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TicketId', full_name='VerifyInRequest.TicketId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=77,
)


_VERIFYOUTRESPONSE = _descriptor.Descriptor(
  name='VerifyOutResponse',
  full_name='VerifyOutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='VerifyOutResponse.Code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='VerifyOutResponse.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='VerifyOutResponse.Content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['VerifyInRequest'] = _VERIFYINREQUEST
DESCRIPTOR.message_types_by_name['VerifyOutResponse'] = _VERIFYOUTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerifyInRequest = _reflection.GeneratedProtocolMessageType('VerifyInRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYINREQUEST,
  __module__ = 'SSOVerifyUrl_pb2'
  # @@protoc_insertion_point(class_scope:VerifyInRequest)
  ))
_sym_db.RegisterMessage(VerifyInRequest)

VerifyOutResponse = _reflection.GeneratedProtocolMessageType('VerifyOutResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYOUTRESPONSE,
  __module__ = 'SSOVerifyUrl_pb2'
  # @@protoc_insertion_point(class_scope:VerifyOutResponse)
  ))
_sym_db.RegisterMessage(VerifyOutResponse)



_SSOVERIFYURL = _descriptor.ServiceDescriptor(
  name='SSOVerifyUrl',
  full_name='SSOVerifyUrl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=148,
  serialized_end=215,
  methods=[
  _descriptor.MethodDescriptor(
    name='VerifyUrl',
    full_name='SSOVerifyUrl.VerifyUrl',
    index=0,
    containing_service=None,
    input_type=_VERIFYINREQUEST,
    output_type=_VERIFYOUTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SSOVERIFYURL)

DESCRIPTOR.services_by_name['SSOVerifyUrl'] = _SSOVERIFYURL

# @@protoc_insertion_point(module_scope)
