# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import sys
sys.path.append('..')
from SSO import SSOVerifyLogin_pb2 as SSOVerifyLogin__pb2


class SSOVerifyLoginStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.VerifyLogin = channel.unary_unary(
        '/SSOVerifyLogin/VerifyLogin',
        request_serializer=SSOVerifyLogin__pb2.VerifyLoginRequest.SerializeToString,
        response_deserializer=SSOVerifyLogin__pb2.VerifyLoginResponse.FromString,
        )


class SSOVerifyLoginServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def VerifyLogin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SSOVerifyLoginServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'VerifyLogin': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyLogin,
          request_deserializer=SSOVerifyLogin__pb2.VerifyLoginRequest.FromString,
          response_serializer=SSOVerifyLogin__pb2.VerifyLoginResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SSOVerifyLogin', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
