# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RedisHelper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RedisHelper.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11RedisHelper.proto\"B\n\x14RedisCacheStrRequest\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\x12\x0e\n\x06\x45xpire\x18\x03 \x01(\x05\"R\n\x14RedisCacheSQLRequest\x12\x0b\n\x03SQL\x18\x01 \x01(\t\x12\x0e\n\x06\x45xpire\x18\x02 \x01(\x05\x12\x1d\n\x08\x43onnArgs\x18\x03 \x01(\x0b\x32\x0b.DbConnArgs\"T\n\nDbConnArgs\x12\x0c\n\x04Host\x18\x01 \x01(\t\x12\x0c\n\x04User\x18\x02 \x01(\t\x12\x10\n\x08PassWord\x18\x03 \x01(\t\x12\n\n\x02\x44\x62\x18\x04 \x01(\t\x12\x0c\n\x04Port\x18\x05 \x01(\x05\"D\n\x12RedisCacheResponse\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x05\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\t2\x89\x01\n\x0bRedisHelper\x12=\n\rRedisCacheStr\x12\x15.RedisCacheStrRequest\x1a\x13.RedisCacheResponse\"\x00\x12;\n\x0bGetSqlValue\x12\x15.RedisCacheSQLRequest\x1a\x13.RedisCacheResponse\"\x00\x62\x06proto3')
)




_REDISCACHESTRREQUEST = _descriptor.Descriptor(
  name='RedisCacheStrRequest',
  full_name='RedisCacheStrRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Key', full_name='RedisCacheStrRequest.Key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Value', full_name='RedisCacheStrRequest.Value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Expire', full_name='RedisCacheStrRequest.Expire', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=87,
)


_REDISCACHESQLREQUEST = _descriptor.Descriptor(
  name='RedisCacheSQLRequest',
  full_name='RedisCacheSQLRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SQL', full_name='RedisCacheSQLRequest.SQL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Expire', full_name='RedisCacheSQLRequest.Expire', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ConnArgs', full_name='RedisCacheSQLRequest.ConnArgs', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=171,
)


_DBCONNARGS = _descriptor.Descriptor(
  name='DbConnArgs',
  full_name='DbConnArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Host', full_name='DbConnArgs.Host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='User', full_name='DbConnArgs.User', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PassWord', full_name='DbConnArgs.PassWord', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Db', full_name='DbConnArgs.Db', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Port', full_name='DbConnArgs.Port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=257,
)


_REDISCACHERESPONSE = _descriptor.Descriptor(
  name='RedisCacheResponse',
  full_name='RedisCacheResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='RedisCacheResponse.Code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='RedisCacheResponse.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='RedisCacheResponse.Content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=327,
)

_REDISCACHESQLREQUEST.fields_by_name['ConnArgs'].message_type = _DBCONNARGS
DESCRIPTOR.message_types_by_name['RedisCacheStrRequest'] = _REDISCACHESTRREQUEST
DESCRIPTOR.message_types_by_name['RedisCacheSQLRequest'] = _REDISCACHESQLREQUEST
DESCRIPTOR.message_types_by_name['DbConnArgs'] = _DBCONNARGS
DESCRIPTOR.message_types_by_name['RedisCacheResponse'] = _REDISCACHERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RedisCacheStrRequest = _reflection.GeneratedProtocolMessageType('RedisCacheStrRequest', (_message.Message,), dict(
  DESCRIPTOR = _REDISCACHESTRREQUEST,
  __module__ = 'RedisHelper_pb2'
  # @@protoc_insertion_point(class_scope:RedisCacheStrRequest)
  ))
_sym_db.RegisterMessage(RedisCacheStrRequest)

RedisCacheSQLRequest = _reflection.GeneratedProtocolMessageType('RedisCacheSQLRequest', (_message.Message,), dict(
  DESCRIPTOR = _REDISCACHESQLREQUEST,
  __module__ = 'RedisHelper_pb2'
  # @@protoc_insertion_point(class_scope:RedisCacheSQLRequest)
  ))
_sym_db.RegisterMessage(RedisCacheSQLRequest)

DbConnArgs = _reflection.GeneratedProtocolMessageType('DbConnArgs', (_message.Message,), dict(
  DESCRIPTOR = _DBCONNARGS,
  __module__ = 'RedisHelper_pb2'
  # @@protoc_insertion_point(class_scope:DbConnArgs)
  ))
_sym_db.RegisterMessage(DbConnArgs)

RedisCacheResponse = _reflection.GeneratedProtocolMessageType('RedisCacheResponse', (_message.Message,), dict(
  DESCRIPTOR = _REDISCACHERESPONSE,
  __module__ = 'RedisHelper_pb2'
  # @@protoc_insertion_point(class_scope:RedisCacheResponse)
  ))
_sym_db.RegisterMessage(RedisCacheResponse)



_REDISHELPER = _descriptor.ServiceDescriptor(
  name='RedisHelper',
  full_name='RedisHelper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=330,
  serialized_end=467,
  methods=[
  _descriptor.MethodDescriptor(
    name='RedisCacheStr',
    full_name='RedisHelper.RedisCacheStr',
    index=0,
    containing_service=None,
    input_type=_REDISCACHESTRREQUEST,
    output_type=_REDISCACHERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSqlValue',
    full_name='RedisHelper.GetSqlValue',
    index=1,
    containing_service=None,
    input_type=_REDISCACHESQLREQUEST,
    output_type=_REDISCACHERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDISHELPER)

DESCRIPTOR.services_by_name['RedisHelper'] = _REDISHELPER

# @@protoc_insertion_point(module_scope)
